### PR TITLE
Add packages used in the Planetary Computer tutorials

### PR DESCRIPTION
**Pull request by stefanistrate**
I'd like to use these 3 packages that often appear in the Planetary Computer tutorials:
- `pystac-client`
- `stackstac`
- `xarray-spatial`

They would make everyone's life easier if they want to use any additional data.

### CODE REVIEW

**Comment by r-b-g-b** [comment]
@stefanistrate Thanks for adding these. Would you mind including versions for each of the packages?

**Comment by stefanistrate** [comment]
`xarray-spatial` works fine as long as `numpy` is downgraded from `1.20.3` to `1.20.0`. I just updated my PR for that.

However, I am now getting some strange errors from Docker. For CPU, am I supposed to build the image with `docker build .`? I get this incompatibility and I don't understand where it's coming from:

```bash
#12 20.82 Encountered problems while solving:
#12 20.82   - package catboost-0.26.1-py36h5fab9bb_0 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed
```

Am I supposed to have python 3.6 installed? Let me know if the CPU/GPU builds complete successfully for you.

**Comment by r-b-g-b** [comment]
I was able to get it to build _without_ `xarray-spatial` by running

```sh
CPU_OR_GPU=cpu make build  # cpu build
CPU_OR_GPU=gpu make build  # gpu build
```

However I do get an error if I include `xarray-spatial`

```
Step 13/19 : RUN mamba env create --name ${CONDA_ENV} -f /home/${NB_USER}/environment.yml      && mamba clean -afy     && rm /home/${NB_USER}/environment.yml     && find ${CONDA_DIR} -follow -type f -name '*.a' -delete     && find ${CONDA_DIR} -follow -type f -name '*.pyc' -delete     && find ${CONDA_DIR} -follow -type f -name '*.js.map' -delete
 ---> Running in 5040c723c53a


Looking for: ['albumentations=1.0.3', 'catboost=0.26.1', 'cudatoolkit==11.1.74=h6bb024c_0', 'cudnn==8.2.1.32=h86fa8c9_0', 'fastai=2.5.0', 'geos=3.9.1', 'geotiff=1.6.0', 'h5py=2.10.0', 'imageio=2.9.0', 'keras=2.4.3', 'loguru=0.5.3', 'mkl=2020.4', 'numba=0.54.1', 'numpy=1.20.0', 'pandas=1.3.1', 'pillow=8.2.0', 'pip=20.3.4', 'pydantic=1.8.2', 'pydap=3.2.2', 'pyepsg=0.4.0', 'pygeos=0.10.1', 'pyproj=3.3.0', 'pystac-client=0.3.1', 'pytest=6.2.4', 'python=3.9.7', 'pytorch-lightning=1.4.1', 'pytorch==1.8.0=cuda111py39h37e5b68_1', 'rasterio=1.2.6', 'scikit-image=0.18.2', 'scikit-learn=0.24.2', 'scipy=1.7.1', 'segmentation-models-pytorch=0.2.0', 'shapely=1.7.1', 'stackstac=0.2.2', 'tifffile=2021.8.8', 'tiledb=2.3.2', 'timm=0.4.12', 'torchvision==0.9.1=py39cuda111hcd06603_1_cuda', 'tqdm=4.62.0', 'typer=0.3.2', 'xarray=0.19.0', 'xarray-spatial=0.3.0']


Encountered problems while solving:
  - package torchvision-0.9.1-py39cuda111hcd06603_1_cuda requires python_abi 3.9.* *_cp39, but none of the providers can be installed
```
One thing to note is that `pystac_client` is already in the environment; it gets installed as a dependency of `planetary_computer`. That said, it's not a bad idea to install that with `conda` and get the version pinned like you do here.

I see a few options:
- Depending on how important `xarray-spatial` is to you, you could consider dropping it from this PR to at least get `stackstac`.
- Try `xarray-spatial` in the `pip` section.

**Comment by stefanistrate** [comment]
@r-b-g-b: I'm happy to remove `xarray-spatial` from this PR and either try again in a new PR, or find a workaround for my code. The tests should pass now.

**Comment by r-b-g-b** [comment]
Good to go, thanks @stefanistrate !

**Pull request merged**
