### PR TITLE
Upgrade segmentation models

### PR DESCRIPTION
**Pull request by MPWARE-TEAM**
Upgrade from 0.2.0 to 0.2.1 to have more Timm backbones

### CODE REVIEW

**Comment by MPWARE-TEAM** [comment]
It looks it fails because of network issue: received unexpected HTTP status: 502 Bad Gateway

**Comment by r-b-g-b** [comment]
Yeah looks like the docker hub registry is being very flaky. I'll keep re-running the job until it finishes.

**Comment by r-b-g-b** [comment]
The build finished finally! @MPWARE-TEAM Could I ask you to link to any release notes for this version so we can be reasonably sure we won't introduce breaking changes to existing code that uses version `0.2.0`? It's a minor version so I don't expect any problems, but just to be sure. Thanks!

**Comment by MPWARE-TEAM** [comment]
Changes logs from 0.2.0 to 0.2.1:
- Universal timm encoder. 400+ pretrained encoders from timm available with tu- prefix. List of available encoders here.
- Minor fixes and improvements.

You already have timm 0.4.12 so it should not break anything.

From: https://github.com/qubvel/segmentation_models.pytorch/releases/tag/v0.2.1

Thanks.

**Pull request merged**
